site_name: OAE PINN Emulator
site_url: https://oae-pinn-emulator.github.io/

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Demo: demo.md
  - Reproduce: reproduce.md

plugins:
  - search

repo_name: OAE-PINN-Emulator/OAE-PINN-Emulator.github.io
repo_url: https://github.com/OAE-PINN-Emulator/OAE-PINN-Emulator.github.io
edit_uri: edit/main/docs/
